trigger:
- master

pool:
  name: 'shinypool'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ACR-DevOpsProdAM001'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'ARM-DEVOPS-PROD-AMER'
    azureResourceGroup: 'devops-prod-aks-am001'
    kubernetesCluster: 'DevOps-PROD-AM001'
    command: 'apply'
    arguments: '-f deploy.yaml'