trigger:
- master

pool:
  name: 'shinypool'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DevOpsAgent Connection'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'DevOpsProdAmer-Agent-serviceprincipal'
    azureResourceGroup: 'DevOps-PROD-AKS-AM001'
    kubernetesCluster: 'DevOps-PROD-AM001'
    command: 'apply'
    arguments: '-f deploy.yaml'